# Generated by Django 5.2 on 2025-05-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temp1', models.FloatField()),
                ('temp2', models.FloatField()),
                ('flow', models.FloatField()),
                ('heater', models.FloatField()),
                ('cooler', models.FloatField()),
                ('setpoint', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='control_pan_timesta_d1b2ef_idx')],
            },
        ),
    ]
