# Generated by Django 5.2 on 2025-05-05 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=50)),
                ('baudrate', models.IntegerField(default=115200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='datalog',
            name='ardduino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control_panel.arduinoconfig'),
            preserve_default=False,
        ),
    ]
