# Generated by Django 5.2 on 2025-05-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_arduinoconfig_datalog_ardduino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalog',
            old_name='ardduino',
            new_name='arduino',
        ),
    ]
